urls.py
from django.urls import path
from . import views

app_name = 'meublog'

urlpatterns=[
    path('', views.ListarPostsView.as_view(), name='listar_posts'),
    path('<slug:slug>/<int:pk>', views.DetalharPostView.as_view(), name='detalhe'),
    path('sharepost/<int:pk>/', views.FormContatoView.as_view(), name='share_post'),
    path('comentarpost/<int:pk>/', views.FormComentarioView.as_view(), name='comentar_post'),
    #path('', views.listar_posts, name='listar_posts'),
    #path('<int:ano>/<int:mes>/<int:dia>/<slug:slug>/', views.detalhar_post, name='detalhe'),
]

models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

#Posts
class PublicadosManager(models.Manager):
    def get_queryset(self):
        return super(PublicadosManager, self).get_queryset().filter(status='publicado')

class Post(models.Model):
    STATUS_CHOICES=(
        ('rascunho', 'Rascunho'),
        ('publicado', 'Publicado')
    )

    object = models.Manager() #gerenciador padrão
    publicados = PublicadosManager() #gerenciador personalizados. Este é chamado na funcão view listar posts

    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=100)
    corpo = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meublog_posts')  
    publicado = models.DateTimeField(default=timezone.now) #Na hora atual
    criado = models.DateTimeField(auto_now_add=True)# No momento em que criar 
    status = models.CharField(max_length=9, choices=STATUS_CHOICES, default='rascunho')
    
    class Meta:
        ordering = ('-publicado',)
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
    
    def __str__(self):
        return self.titulo

#Comentarios
class AtivosManager(models.Manager):
    def get_queryset(self):
        return super(AtivosManager, self).get_queryset().all()   

class Comentario(models.Model):
    STATUS_CHOICES=(
        (True, 'Ativo'),
        (False, 'Desativo')
    )

    ativosG = AtivosManager()#Gerenciador

    nome = models.CharField(max_length=100)
    email = models.EmailField()
    corpo = models.CharField(max_length=255)
    criado = models.DateTimeField(auto_now_add=True)
    atualizado = models.DateTimeField(auto_now_add=True)
    ativo = models.BooleanField(choices=STATUS_CHOICES, default=True)
    fk_post = models.ForeignKey(Post, on_delete=models.CASCADE)#Chave Estrangeira

    def __str__(self):
        return self.corpo

forms.py
from django import forms
from django.core.mail import EmailMessage
from django.forms.fields import EmailField
from .models import Comentario, Post

#Compartilhar post
class EmailPost(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    destino = forms.EmailField()
    coments = forms.CharField(required=False, widget=forms.Textarea)

    def enviar_email(self, meupost):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        destino = self.cleaned_data['destino']
        coments = self.cleaned_data['coments']

        conteudo = f"Recomendo ler o post: {meupost.titulo} Comentarios: {coments}"

        mail = EmailMessage(
            subject=f"Recomendo este Post",
            body=conteudo,
            from_email='contato@meublog.com.br',
            to=[destino,],
            headers={'Reply-To': email}
        )

        mail.send()

#Comentario
class ComentarioForm(forms.Form):
    nome = forms.CharField(max_length=100)
    email = forms.EmailField()
    corpo = forms.CharField(required=True, widget=forms.Textarea)

    def enviar_comentario(self, post):
        nome = self.cleaned_data['nome']
        email = self.cleaned_data['email']
        corpo = self.cleaned_data['corpo']

        comentario = Comentario()
        comentario.nome = nome
        comentario.email = email
        comentario.corpo = corpo
        comentario.fk_post = Post.publicados.get(id=post.id)
        comentario.save()

        

views.py
from django.core.mail import message
from django.shortcuts import render, get_object_or_404
from .models import Post, Comentario
from .forms import ComentarioForm, EmailPost
from django.urls import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView, FormView
from django.contrib import messages

#Posts
class ListarPostsView(ListView):
    queryset = Post.publicados.all()
    context_object_name = 'posts'
    paginate_by = 2
    template_name = 'meublog/post/listarposts.html'


class DetalharPostView(DetailView):
    model = Post
    template_name = 'meublog/post/detalharpost.html'    
    
    def get_context_data(self, **kwargs):
        #Pega o contexto da página
        context = super(DetailView, self).get_context_data(**kwargs)
        context['comentarios'] = Comentario.ativosG.filter(fk_post=kwargs.get('object').id)
        return context

#Form do comentarios
class FormComentarioView(FormView):
    template_name = 'meublog/post/comentar.html'
    success_url = reverse_lazy('meublog:listar_posts')
    form_class = ComentarioForm

    def get_post(self, id_post):
        try:
            return Post.publicados.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'O post não existe')
            reverse_lazy('meublog:listar_posts')
    
    def get_context_data(self, **kwargs):
        context = super(FormComentarioView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context
    
    def form_valid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        form.enviar_comentario(meupost)
        messages.success(self.request, f'Comentario enviado com sucesso')
        return super(FormComentarioView, self).form_valid(form, *args, **kwargs)

    
    def form_invalid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        messages.error(self.request, f'Comentario com erro ao enviar')
        return super(FormComentarioView, self).form_invalid(form, *args, **kwargs)

#Contato form
class FormContatoView(FormView):
    template_name = 'meublog/post/sharepost.html'
    form_class = EmailPost
    success_url = reverse_lazy('meublog:listar_posts')

    def get_post(self, id_post):
        try:
            return Post.publicados.get(pk=id_post)
        except Post.DoesNotExist:
            messages.error(self.request, 'O post não existe')
            reverse_lazy('meublog:listar_posts')

    def get_context_data(self, **kwargs):
        context = super(FormContatoView, self).get_context_data(**kwargs)
        context['post'] = self.get_post(self.kwargs['pk'])
        return context

    def form_valid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        form.enviar_email(meupost)
        messages.success(self.request, f'Post {meupost.titulo} enviado com sucesso')
        return super(FormContatoView, self).form_valid(form, *args, **kwargs)

    
    def form_invalid(self, form, *args, **kwargs):
        meupost = self.get_context_data()['post']
        messages.error(self.request, f'Post {meupost.titulo} erro ao enviar')
        return super(FormContatoView, self).form_invalid(form, *args, **kwargs)
'''
def listar_posts(request):
    posts = Post.publicados.all() #Este é o gerenciador criado
    return render(request, 'meublog/post/listarposts.html', {'posts': posts})

def detalhar_post(request, ano, mes, dia, slug, pk):
    post = get_object_or_404(Post, slug=slug, status='publicado', publicado__year=ano, publicado__month=mes, publicado__day=dia)
    comentarios = Comentario.ativosG.filter(ativo=True, fk_post=pk)
    return render(request, 'meublog/post/detalharpost.html', {'post': post, 'comentarios': comentarios})
'''

templates/meublog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/meublog.css' %}">
</head> 
<body>
<div class="page">
    <div id="content">
        <div class="header">
            <div id="logo">
                <h1>Blog JC</h1>
                <p>Dev solutions</p>
            </div>
            <div id="menu">
                <a href="/">Posts</a>
                <a href="/admin">Fazer Login</a>
            </div>
        </div>
        {% block conteudo %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Meinha Sidebar</h2>
        <p>conteudo sidebar</p>
    </div>
</div>
</body>
</html>

templates/meublog/post/comentar.html
{% extends 'meublog/base.html' %}
{% block titulo %}
    Comente
{% endblock %}

{% block conteudo %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Comentar">
    </form>
{% endblock %}

templates/meublog/post/detalharpost.html
{% extends 'meublog/base.html' %}
{% block titulo %}
    {{ post.titulo }}
{% endblock %}

{% block conteudo %}
<div class="post">
    <h1>{{ post.titulo }}</h1>
    <p class="date">
        Publicado em {{ post.publicado }} por {{ post.autor }}
    </p>
    <p>
        {{ post.corpo|linebreaks }}
    </p>
    <div class="post-action">
        <a href="{% url 'meublog:share_post' post.id %}">Enviar este Post</a>
        <a href="{% url 'meublog:comentar_post' post.id %}">Comentar</a>
    </p>
    </div>
</div>
<div class="comentario-post">
    <h3>Comentarios:</h3>
    {% if comentarios %}
        {% for c in comentarios %}
        <div class="comentario">
                <p class="date">Criado em: {{ c.criado }} por: {{ c.nome }}</p>
                <p class="date">Atualizado em: {{ c.atualizado }}</p>
                <p class="corpo-comentario">{{ c.corpo }}</p>
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

templates/meublog/post/listarposts.html
{% extends 'meublog/base.html' %}
{% block titulo %}
    << Meu Blog >>
{% endblock %}
{% block conteudo %}
<div id="content">

    {% if messages %}
        {% for m in messages %}
            <p>{{ m }}</p>
        {% endfor %}
    {% endif %}
    
    {% for p in posts %}
    <div class="box-post">
        <h2>
            <a href="{% url 'meublog:detalhe' p.slug p.id %}">{{ p.titulo }}</a>
        </h2>
        <p class="date">
            Publicado em {{ p.publicado }} por {{ p.autor }}
        </p>
        <p>
            {{ p.corpo|truncatewords:15|linebreaks }}
        </p>
    </div>
    {% endfor %}


    {% include 'paginacao.html' with page=page_obj %}
</div>
{% endblock %}

templates/meublog/post/sharepost.html
{% extends 'meublog/base.html' %}
{% block title %}
    Share Post
{% endblock %}

{% block conteudo %}
    <h1>Enviar post: {{ post.titulo }} por email</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

templates/paginacao.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}"><--</a>
        {% endif %}
        <span class="current">
            Página {{ page.number }} de {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">--></a>
        {% endif %}
    </span>
</div>